apiVersion: v2
appVersion: v0.0.1
description: Keycloak Realm reconciler
home: https://github.com/DoodleScheduling/k8skeycloak-controller
maintainers:
- name: devops
  email: devops@doodle.com
keywords:
- kubernetes-controller
- http-keycloak
- request-clone
name: k8skeycloak-controller
sources:
- https://github.com/DoodleScheduling/k8skeycloak-controller
version: 0.1.1
