apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8skeycloak-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "k8skeycloak-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "k8skeycloak-controller.chart" . }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "k8skeycloak-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type }}
